### ISSUE TITLE
Problems running on my own data set

### ISSUE THREAD

**Issue by pythonyyds-byte** [charigyang/motiongrouping#21]
My program run created the following problems：
Traceback (most recent call last):
  File "predict.py", line 117, in <module>
    predict(args)
  File "predict.py", line 54, in predict
    model.load_state_dict(torch.load(args.model))
  File "/home/fjs/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/modules/module.py", lin               e 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RAFT:
        Missing key(s) in state_dict: "fnet.conv1.weight", "fnet.conv1.bias",..........
        Unexpected key(s) in state_dict: "module.fnet.conv1.weight", "module.fnet.conv1.bias",.........

I configured anaconda in the virtual environment based on the information in the file README.md, where pytorch==1.7.0, cuda=110, which is suitable for the GPU model I used. python==3.7. No other third-party library versions are specified. By the way, I'm running on a single GPU, and I don't know if the above information can answer my questions.

**Comment by pythonyyds-byte** [comment]
I am sorry that I neglected to read the data relationship in the dictionary. I think I have a solution to the problem.
